import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { encode as base64Encode } from "https://deno.land/std@0.168.0/encoding/base64.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface ContactData {
  customer_name: string;
  mobile_number: string;
  branch: string;
}

interface ReceiptData {
  customer_name: string;
  mobile_number: string;
  branch: string;
  receipt_date: string;
  total_amount: number;
  items: string;
}

function generateContactsCSV(contacts: ContactData[]): string {
  const header = "Sr No,Customer Name,Mobile Number,Branch\n";
  const rows = contacts
    .map((c, i) => `${i + 1},"${c.customer_name}","${c.mobile_number}","${c.branch}"`)
    .join("\n");
  return header + rows;
}

function generateReceiptsCSV(receipts: ReceiptData[]): string {
  const header = "Sr No,Customer Name,Mobile Number,Branch,Receipt Date,Amount,Items\n";
  const rows = receipts
    .map((r, i) => `${i + 1},"${r.customer_name}","${r.mobile_number}","${r.branch}","${r.receipt_date}",${r.total_amount},"${r.items}"`)
    .join("\n");
  return header + rows;
}

function buildEmailHTML(
  contacts: ContactData[],
  receipts: ReceiptData[],
  branchFilter: string,
  monthFilter: string,
  dateFrom?: string,
  dateTo?: string,
): string {
  const branchLabel = branchFilter === "all" ? "All Branches" : branchFilter;
  const monthLabel = monthFilter === "all" ? "All Months" : monthFilter;
  const dateLabel = (dateFrom && dateFrom !== "all") || (dateTo && dateTo !== "all")
    ? `${dateFrom && dateFrom !== "all" ? dateFrom : "Start"} to ${dateTo && dateTo !== "all" ? dateTo : "Present"}`
    : "";

  const contactRows = contacts
    .map(
      (c, i) => `
    <tr style="background:${i % 2 === 0 ? "#f9fafb" : "#ffffff"}">
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${i + 1}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.customer_name}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.mobile_number}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.branch}</td>
    </tr>`
    )
    .join("");

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#1a1a1a;color:#ffffff;padding:20px;border-radius:8px 8px 0 0">
        <h2 style="margin:0">Customer Contact & Receipt Report</h2>
        <p style="margin:4px 0 0;opacity:0.8">Branch: ${branchLabel} | Period: ${monthLabel}${dateLabel ? ` | Date: ${dateLabel}` : ""}</p>
      </div>
      <div style="padding:20px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px">
        <p style="color:#6b7280">Total Contacts: <strong>${contacts.length}</strong> | Total Receipts: <strong>${receipts.length}</strong></p>
        <p style="color:#6b7280;font-size:13px">📎 Two CSV files are attached:<br/>
        1. <strong>contacts.csv</strong> - Customer contact details (branch-wise)<br/>
        2. <strong>receipts.csv</strong> - Patient receipt history</p>
        <h3 style="margin:16px 0 8px;color:#1a1a1a">Contact Summary</h3>
        <table style="width:100%;border-collapse:collapse;margin-top:12px">
          <thead>
            <tr style="background:#f3f4f6">
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">#</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Name</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Mobile</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Branch</th>
            </tr>
          </thead>
          <tbody>${contactRows}</tbody>
        </table>
        <p style="margin-top:16px;color:#9ca3af;font-size:12px">
          Auto-generated by Digital Receipt Desk
        </p>
      </div>
    </div>`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to_email, contacts, receipts, branch_filter, month_filter, date_from, date_to } = await req.json();

    if (!to_email || ((!contacts || contacts.length === 0) && (!receipts || receipts.length === 0))) {
      throw new Error("Missing required fields");
    }

    const gmailUser = Deno.env.get("GMAIL_USER");
    const gmailPass = Deno.env.get("GMAIL_APP_PASSWORD");

    if (!gmailUser || !gmailPass) {
      throw new Error("Gmail credentials not configured");
    }

    const branchLabel = branch_filter === "all" ? "All Branches" : branch_filter;
    const monthLabel = month_filter === "all" ? "All Months" : month_filter;
    const dateLabel = (date_from && date_from !== "all") || (date_to && date_to !== "all")
      ? ` (${date_from !== "all" ? date_from : "Start"} to ${date_to !== "all" ? date_to : "Present"})`
      : "";
    const subject = `Customer Contacts & Receipts - ${branchLabel} - ${monthLabel}${dateLabel}`;

    const html = buildEmailHTML(contacts, receipts || [], branch_filter, month_filter, date_from, date_to);

    // Generate CSV files
    const contactsCSV = generateContactsCSV(contacts);
    const receiptsCSV = generateReceiptsCSV(receipts || []);

    const { SMTPClient } = await import("https://deno.land/x/denomailer@1.6.0/mod.ts");

    const client = new SMTPClient({
      connection: {
        hostname: "smtp.gmail.com",
        port: 465,
        tls: true,
        auth: {
          username: gmailUser,
          password: gmailPass,
        },
      },
    });

    const attachments = [
      {
        filename: `contacts-${branch_filter}-${month_filter}.csv`,
        content: base64Encode(new TextEncoder().encode(contactsCSV)),
        encoding: "base64" as const,
        contentType: "text/csv",
      },
    ];

    if (receipts && receipts.length > 0) {
      attachments.push({
        filename: `receipt-history-${branch_filter}-${month_filter}.csv`,
        content: base64Encode(new TextEncoder().encode(receiptsCSV)),
        encoding: "base64" as const,
        contentType: "text/csv",
      });
    }

    await client.send({
      from: gmailUser,
      to: to_email,
      subject: subject,
      content: "auto",
      html: html,
      attachments: attachments,
    });

    await client.close();

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    console.error("Error sending email:", error);
    const msg = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ success: false, error: msg }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
