import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface ContactData {
  customer_name: string;
  mobile_number: string;
  branch: string;
}

// Simple SMTP sender using Deno TCP
async function sendEmailViaSMTP(
  to: string,
  subject: string,
  htmlBody: string
) {
  const gmailUser = Deno.env.get("GMAIL_USER");
  const gmailPass = Deno.env.get("GMAIL_APP_PASSWORD");

  if (!gmailUser || !gmailPass) {
    throw new Error("Gmail credentials not configured");
  }

  // Use Gmail SMTP via fetch to a mail relay
  // Since Deno edge functions can't do raw TCP, we'll use the Gmail API approach
  // Actually, let's use a simple approach with base64 encoded email and Gmail SMTP relay

  const encoder = new TextEncoder();

  // Build the email
  const boundary = "boundary_" + Date.now();
  const emailLines = [
    `From: ${gmailUser}`,
    `To: ${to}`,
    `Subject: ${subject}`,
    `MIME-Version: 1.0`,
    `Content-Type: text/html; charset=UTF-8`,
    ``,
    htmlBody,
  ];

  const rawEmail = emailLines.join("\r\n");
  const encodedEmail = btoa(unescape(encodeURIComponent(rawEmail)))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");

  // Use nodemailer-like approach via SMTP
  // Since we can't do raw TCP in edge functions, use the Deno smtp client
  const { SMTPClient } = await import("https://deno.land/x/denomailer@1.6.0/mod.ts");

  const client = new SMTPClient({
    connection: {
      hostname: "smtp.gmail.com",
      port: 465,
      tls: true,
      auth: {
        username: gmailUser,
        password: gmailPass,
      },
    },
  });

  await client.send({
    from: gmailUser,
    to: to,
    subject: subject,
    content: "auto",
    html: htmlBody,
  });

  await client.close();
}

function buildEmailHTML(
  contacts: ContactData[],
  branchFilter: string,
  monthFilter: string,
  dateFrom?: string,
  dateTo?: string,
): string {
  const branchLabel = branchFilter === "all" ? "All Branches" : branchFilter;
  const monthLabel = monthFilter === "all" ? "All Months" : monthFilter;
  const dateLabel = (dateFrom && dateFrom !== "all") || (dateTo && dateTo !== "all")
    ? `${dateFrom && dateFrom !== "all" ? dateFrom : "Start"} to ${dateTo && dateTo !== "all" ? dateTo : "Present"}`
    : "";

  const rows = contacts
    .map(
      (c, i) => `
    <tr style="background:${i % 2 === 0 ? "#f9fafb" : "#ffffff"}">
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${i + 1}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.customer_name}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.mobile_number}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${c.branch}</td>
    </tr>`
    )
    .join("");

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#1a1a1a;color:#ffffff;padding:20px;border-radius:8px 8px 0 0">
        <h2 style="margin:0">Customer Contact Report</h2>
        <p style="margin:4px 0 0;opacity:0.8">Branch: ${branchLabel} | Period: ${monthLabel}${dateLabel ? ` | Date: ${dateLabel}` : ""}</p>
      </div>
      <div style="padding:20px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px">
        <p style="color:#6b7280">Total Contacts: <strong>${contacts.length}</strong></p>
        <table style="width:100%;border-collapse:collapse;margin-top:12px">
          <thead>
            <tr style="background:#f3f4f6">
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">#</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Name</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Mobile</th>
              <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db">Branch</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
        <p style="margin-top:16px;color:#9ca3af;font-size:12px">
          Auto-generated by Digital Receipt Desk
        </p>
      </div>
    </div>`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to_email, contacts, branch_filter, month_filter, date_from, date_to } = await req.json();

    if (!to_email || !contacts || contacts.length === 0) {
      throw new Error("Missing required fields");
    }

    const branchLabel = branch_filter === "all" ? "All Branches" : branch_filter;
    const monthLabel = month_filter === "all" ? "All Months" : month_filter;
    const dateLabel = (date_from && date_from !== "all") || (date_to && date_to !== "all")
      ? ` (${date_from !== "all" ? date_from : "Start"} to ${date_to !== "all" ? date_to : "Present"})`
      : "";
    const subject = `Customer Contacts - ${branchLabel} - ${monthLabel}${dateLabel}`;

    const html = buildEmailHTML(contacts, branch_filter, month_filter, date_from, date_to);

    await sendEmailViaSMTP(to_email, subject, html);

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    console.error("Error sending email:", error);
    const msg = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ success: false, error: msg }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
